FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.25-openshift-4.22 AS builder
WORKDIR /go/src/github.com/openshift/machine-api-provider-aws
COPY . .
# VERSION env gets set in the openshift/release image and refers to the golang version, which interfers with our own
RUN unset VERSION \
    && GOPROXY=off NO_DOCKER=1 make build && \
    gzip  /go/src/github.com/openshift/machine-api-provider-aws/openshift-tests/bin/machine-api-provider-aws-tests-ext

FROM registry.ci.openshift.org/ocp/4.22:base-rhel9
COPY --from=builder /go/src/github.com/openshift/machine-api-provider-aws/bin/machine-controller-manager /
COPY --from=builder /go/src/github.com/openshift/machine-api-provider-aws/bin/termination-handler /
COPY --from=builder /go/src/github.com/openshift/machine-api-provider-aws/openshift-tests/bin/machine-api-provider-aws-tests-ext.gz /

LABEL io.openshift.release.operator true
